version: "3.8"
services:
  fastapi:
    container_name: fastapi_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    env_file:
      - ./.env
    depends_on:
      - postgres
  postgres:
    container_name: postgres_db
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    # no need to expose DB port, host machine doesn't access it
    # ports:
    #   - 5432:5432

# names volumes
volumes:
  postgres_data:
