"""Add done todo field

Revision ID: 85e48d77e3ce
Revises: dee1aa0965a0
Create Date: 2023-03-07 23:29:59.644465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85e48d77e3ce'
down_revision = 'dee1aa0965a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('done', sa.Boolean(), nullable=True))
    op.add_column('todos', sa.Column('time_done', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'time_done')
    op.drop_column('todos', 'done')
    # ### end Alembic commands ###
