apiVersion: v1
kind: ConfigMap
metadata:
  name: fastapi-env
data:
  ENVIRONMENT: "dev"

  USE_ALEMBIC: "true"

  # all the next variables should be defined as Secrets
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_DB: "postgres"
  POSTGRES_SERVER: "postgres-service.default"
  POSTGRES_PORT: "5432"
