# Service to expose the FastAPI backend outside of the cluster
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
# Deployment to create and handle the pods running
# the FastAPI backend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-app
  template:
    metadata:
      labels:
        app: fastapi-app
    spec:
      containers:
        - name: fastapi-cont
          image: mbrignone/fastapi-app
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: fastapi-env
